### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by leijue222** [Ursinus-CS371-S2021/HW3_DTW_AudioAlignment#1]
Hi!
The README seems to lack some steps, so I don't know how to align A(gettysburg1.wav) to B(gettysburg2.wav) audio file.

**Comment by ctralie** [comment]
Hi, thanks for your interest in this!  Have a look at the writeup here:

http://www.ctralie.com/Teaching/CS371_S2021/Assignments/HW3_DTW_AudioAlignment/

I'll link to it from the readme.
Thanks,
Chris

**Comment by leijue222** [comment]
I have done it. But I don't know why the aligned audio file will generate noise.
Example is here: [gettysburg2.zip](https://github.com/Ursinus-CS371-S2021/HW3_DTW_AudioAlignment/files/6140046/gettysburg2.zip)
`gettysburg2_1_fastdtw.mp3` is download from http://www.ctralie.com/Teaching/CS371_S2021/Assignments/HW3_DTW_AudioAlignment/
 I reference the link to generate `gettysburg22gettysburg1.wav`.

Put on headphones and listen to the left channel, there is noise in both files.
How can I solve it?

**Comment by ctralie** [comment]
Try running it in jupyter instead
http://www.ctralie.com/Teaching/CS371_S2021/Assignments/HW3_DTW_AudioAlignment/index.html#jupyter

**Comment by leijue222** [comment]
Thanks for your reply.
Whether it is played with Jupyter, Ubuntu, or Windows,  the result is the same. 
The DTW processed audio is **successfully aligned**, but I have no idea to **improve the audio quality, eliminate noise**.

**Comment by ctralie** [comment]
Are you talking about some of the minor clicking that happens to line them up?  This is a totally vanilla system for the purposes of teaching.  You may be interested in the rubberband library:
https://breakfastquay.com/rubberband/

**Comment by ctralie** [comment]
Also, I have a much faster library for doing DTW
https://pypi.org/project/linmdtw/

Again, not sure why you're so focused on the class assignment, but it's cool that you tried it!

**Comment by leijue222** [comment]
Wow, `linmdtw` is wonderful! I love it!
Thank you for your patience in teaching and project recommendations. 
:rose: Have a good time~

**Comment by ctralie** [comment]
My pleasure!  I'm flattered that you checked out the assignment!
